//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FewMain.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class FewMainArticle
    {
        public int Id { get; set; }
        public string Author { get; set; }
        public Nullable<int> Type { get; set; }
        public string WebTitle { get; set; }
        public string WebKeyword { get; set; }
        public string WebDescription { get; set; }
        public string Title { get; set; }
        public string Contents { get; set; }
        public Nullable<int> ClickCount { get; set; }
        public Nullable<int> Tag { get; set; }
        public Nullable<System.DateTime> AddTime { get; set; }
        public Nullable<int> AppId { get; set; }
    }
}
