//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FewMain.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class FewMainProduct
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FewMainProduct()
        {
            this.FewMainEvaluation = new HashSet<FewMainEvaluation>();
        }
    
        public int Id { get; set; }
        public string ProName { get; set; }
        public int ProTypeId { get; set; }
        public string ProTypeName { get; set; }
        public int ProSeriesId { get; set; }
        public string ProSeriesName { get; set; }
        public string ImgSrcList { get; set; }
        public string ProImgDetail { get; set; }
        public string WebTitle { get; set; }
        public string WebKeyword { get; set; }
        public string WebDescription { get; set; }
        public string DefaultSKU { get; set; }
        public string SetSKU { get; set; }
        public int IsShow { get; set; }
        public System.DateTime AddTime { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FewMainEvaluation> FewMainEvaluation { get; set; }
    }
}
