//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FewMain.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class FewMainSku
    {
        public int Id { get; set; }
        public string SKUNo { get; set; }
        public decimal Weight { get; set; }
        public string Shape { get; set; }
        public string Color { get; set; }
        public string Clarity { get; set; }
        public string Cut { get; set; }
        public string Polishing { get; set; }
        public string Symmetry { get; set; }
        public string Fluorescence { get; set; }
        public decimal Price { get; set; }
        public string Coffee { get; set; }
        public string Milk { get; set; }
        public Nullable<System.DateTime> AddTime { get; set; }
        public Nullable<System.DateTime> UpdateTime { get; set; }
    }
}
